@echo off

set LANGUAGE=Espanol


echo %LOADING% %LANGUAGE%

set LOADING=Cargando
set CONFIG_FILE=Configuracion

set YES=Si
set NO=No
set TCF=convertir apps a formato title.cfg antes de instalar
set MAKE_VMC_BEFORE=Crear VMC...
set ADMIN_PRIV=Solicitando permisos de administrador...
set BASIC_CHOICE="Seleccione:"

set Transfer=Transferir
set Applications=Applicaciones:
set Configs=Configuracion:
set Artwork=Caratulas:
set Cheats=Cheats:
set Themes=Temas:

set INSTALLING=Instalando


set EST_FILE_SIZE=Tamano estimado:
set Files=Archivos:
set Size=Tamano:
set IS_EMPTY=Esta vacio...
set CFG_EMPTY=No hay archivos .CFG dentro...
set CHT_EMPTY=No hay archivos .CHT dentro...
set VMC_EMPTY=No hay archivos .BIN dentro...

set VMC_SIZE_ASK=elegir tamano
set VMC_NAME_ASK=Escriba el nommbre de la VMC sin extension


set SEARCHING_OPLPART=Detectando Particion:
set DETECTED_OPLPART=Particion Detectada
set MISSING_OPLPART=Particion NO Detectada

set FORMAT_OPLPART=Asegurate de que la particion exista y este en formato PFS

set BAT_DEPS=Comprobando dependencias...
set DEPS_MISSING=Faltante
set DEPS_FOUND=encontrado

set HDD_SCAN=Buscando HDDs en formato Playstation 2:
set HDD_NOT_FOUND1=No se detectan HDDs en formato Playstation 2
set HDD_NOT_FOUND2=Comprobar conexion y formato del HDD


set COMPLETED=Completado...
set CREAT_LOG=Creando Log

set EXTRACTING_WIDE=Extrayendo Hacks de Pantalla Panoramica...
set EXTRACTED_WIDE=Extraidos en total:
set INST_WIDE=Instalar Hacks de Pantalla Panoramica

set NO_INTERNET=No se puede determinar si hay coneccion a internet
set INTERNET_CHECK=Checkeando conexion a internet
set DOWNLOAD_CHEATS=Descargar Hacks de Pantalla Panoramica?