@echo off

set LANGUAGE=English


echo %LOADING% %LANGUAGE%

set LOADING=Loading
set CONFIG_FILE=Config File

set YES=Yes
set NO=NO
set TCF=Convert apps into title.cfg format before install
set MAKE_VMC_BEFORE=Create VMC Before Transfering...
set ADMIN_PRIV=Requesting Administrative Privileges...
set BASIC_CHOICE="Select Option:"

set Transfer=Transfer
set Applications=Applications:
set Configs=Configs:
set Artwork=Artwork:
set Cheats=Cheats:
set Themes=Themes:

set INSTALLING=Installing


set EST_FILE_SIZE=Estimating File Size:
set Files=Files:
set Size=Size:
set IS_EMPTY=Source Not Detected...
set CFG_EMPTY=No .CFG Files Inside...
set CHT_EMPTY=No .CHT Files Inside...
set VMC_EMPTY=No .BIN Files Inside...

set VMC_SIZE_ASK=choose Size
set VMC_NAME_ASK=Write VMC Name (without extension)...


set SEARCHING_OPLPART=Detecting Partition:
set DETECTED_OPLPART=Partition Detected
set MISSING_OPLPART=Partition NOT Detected

set FORMAT_OPLPART=Make sure if partition exists and it is on PFS Format

set BAT_DEPS=Checking Batch Dependencies...
set DEPS_MISSING=Missing
set DEPS_FOUND=Confirmed

set HDD_SCAN=Scanning for Playstation 2 HDDs:
set HDD_NOT_FOUND1=Playstation 2 HDD Not Detected
set HDD_NOT_FOUND2=Make sure HDD Is well connected and formatted


set COMPLETED=Completed...
set CREAT_LOG=Creating Log

set EXTRACTING_WIDE=Extracting Widescreen Hacks...
set EXTRACTED_WIDE=recovered a total of:
set INST_WIDE=Download/Install widescreen cheats

set NO_INTERNET=Can't determine internet connection
set INTERNET_CHECK=checking internet connection
set DOWNLOAD_CHEATS=Download Latest Widescreen Cheats?

set DOWNLOAD_HDLBINST=5. Download HDL Batch Installer

set MENU_1=1. Transfer PS1 Games
set MENU_2=2. Transfer PS2 Games
set MENU_3=3. Transfer APPS,ART,CFG,CHT,VMC,THM
set MENU_4=4. Transfer POPS Binaries

set MENU_7=7. Backup PS1 Games
set MENU_8=8. Backup PS2 Games
set MENU_9=9. Backup ART,CFG,CHT,VMC
set MENU_10=10. Advanced Menu
set MENU_11=11. Exit

set DOWNLOAD=Download
set LATEST_VER=Latest Version